
# Swagger
SwaggerUISettings:
  Active: true

# GraphQL 
GraphQLSettings:
  SchemaName: "appschema"
  ApiPath: "/api/graphql"
  IncludeExceptionDetails: true
  ExecutionTimeoutSeconds: 30
  StrictValidation: false
  SortFieldsByName: true
  RemoveUnreachableTypes: true
  PagingSettings:
    DefaultPageSize: 10
    MaxPageSize: 100
    IncludeTotalCount: true
  BananaCakePopSettings:
    UiPath: "/ui/graphql/"
    ActiveUi: true
  GraphQLVoyagerSettings:
    UiPath: "/ui/graphql/voyager"
    ApiPath: "/api/graphql"
    ActiveUi: true

# Infrastructure
InfrastructureSettings:
  DataBase1:
    ConnectionStrings:
      PrimaryConnectionString: "Data Source=../../app.db"

# Cors
CorsSettings:
  PolicyName: MainPolicy
  AllowedOrigins:
    - http://localhost:5173/
  AllowedHeaders:
    - Autorization
    - Content-Type
  AllowedMethods:
    - GET
    - POST

# Logs
Logging:
  IncludeScopes: false
  LogLevel:
    Default: Debug
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information

Serilog:
  MinimumLevel:
    Default: "Debug"
    Override:
      "System": "Warning"
      "Microsoft": "Warning"
  Enrich: ["FromLogContext", "WithMachineName", "WithThreadId"]
